---
# OS RELEASE: RHEL 7 and RHEL 8
# SAP Note: 2526952 - Red Hat Enterprise Linux for SAP Solutions
# prerequisite: package tuned-profiles-sap is installed (see vars/RedHat.yml)

# Configure tuned to use profile "sap-netweaver"

- name: Get status of tuned
  command: systemctl status tuned
  register: tuned_status
  ignore_errors: yes
  changed_when: no

- name: Assert that tuned is enabled and started
  assert:
    that:
      - "'active (running)' in tuned_status.stdout"
      - "'/usr/lib/systemd/system/tuned.service; enabled' in tuned_status.stdout"
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Get active tuned profile
  command: bash -lc "/usr/sbin/tuned-adm active | awk '/:/{print $NF}'"
  check_mode: no
  register: current_profile
  changed_when: false

- debug:
    var: current_profile.stdout_lines, current_profile.stderr_lines

- name: Assert that tuned profile sap-netweaver is currently active
  assert:
    that:
      - current_profile.stdout == 'sap-netweaver'
    fail_msg: "The tuned profile >sap-netweaver< is currently not active.
      Currently active profile: >{{ current_profile.stdout }}<."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

...
