---
# tasks file for sap-netweaver-preconfigure configuration

- name: list of required SAP Notes
  debug:
    var: __sap_netweaver_preconfigure_assert_sapnotes | difference([''])

- name: include configuration actions for required sapnotes
  include_tasks: "sapnote/assert-{{ item }}.yml"
  with_items: "{{ __sap_netweaver_preconfigure_assert_sapnotes | difference(['']) }}"

- name: Warn if swap space check will be skipped
  fail:
    msg: "Warning: The swap space check will be skipped because variable
      sap_netweaver_preconfigure_assert_fail_if_not_enough_swap_space_configured is set to no!"
  when: not sap_netweaver_preconfigure_assert_fail_if_not_enough_swap_space_configured
  ignore_errors: true

- name: Assert that enough swap space is configured
  assert:
    that:
      - ansible_swaptotal_mb >= 20480
    fail_msg: "FAIL: The system has only {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is less than the minimum required amount of 20480 MB for SAP NetWeaver!"
    success_msg: "PASS: The system has {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is equal to or more than the minimum required amount of 20480 MB for SAP NetWeaver."
  when: sap_netweaver_preconfigure_assert_fail_if_not_enough_swap_space_configured
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

...
